name: llm-client-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.10
  - pip
  - pip:
      - python-dotenv>=1.0.1
      - openai>=1.51.0
      - groq>=0.5.0
      - ollama>=0.1.9
      - llama-index

