name: Link Checker

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 1 * *" # Runs on the 1st of every month at 00:00

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2.3.0
        with:
          # Check all markdown files in the repository
          # Exclude domains that often return 429 or 403 Forbidden to automated checkers
          args: --verbose --no-progress --exclude "openai.com" --exclude "medium.com" --exclude "gopenai.com" --exclude "github.com/ollama/ollama" --exclude "deeplearning.ai" --exclude "ki.th-koeln.de" --exclude "coursera.org" --exclude "huggingface.co" "**/*.md"
          # Fail the action if broken links are found
          failIfEmpty: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
