# .github/workflows/lint.yml
name: Code Quality

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'requirements.txt'
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'requirements.txt'

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-lint-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-lint-
      
      - name: Install linting dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black mypy
      
      - name: Lint with Ruff
        run: |
          # Ruff ist schneller und moderner als flake8
          ruff check . --output-format=github
        continue-on-error: false
      
      - name: Check formatting with Black
        run: |
          black --check --diff .
        continue-on-error: false
      
      - name: Type check with mypy
        run: |
          mypy llm_client --ignore-missing-imports --no-strict-optional
        continue-on-error: true

  security:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit[toml]
      
      - name: Run security checks with Bandit
        run: |
          bandit -r llm_client/ -ll -f github
        continue-on-error: true
        